// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baronchain/pqc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryKyberPublicKeyRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryKyberPublicKeyRequest) Reset()         { *m = QueryKyberPublicKeyRequest{} }
func (m *QueryKyberPublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryKyberPublicKeyRequest) ProtoMessage()    {}
func (*QueryKyberPublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b3d2129c030bc, []int{0}
}
func (m *QueryKyberPublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKyberPublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKyberPublicKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKyberPublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKyberPublicKeyRequest.Merge(m, src)
}
func (m *QueryKyberPublicKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryKyberPublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKyberPublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKyberPublicKeyRequest proto.InternalMessageInfo

func (m *QueryKyberPublicKeyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryKyberPublicKeyResponse struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *QueryKyberPublicKeyResponse) Reset()         { *m = QueryKyberPublicKeyResponse{} }
func (m *QueryKyberPublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryKyberPublicKeyResponse) ProtoMessage()    {}
func (*QueryKyberPublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b3d2129c030bc, []int{1}
}
func (m *QueryKyberPublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKyberPublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKyberPublicKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKyberPublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKyberPublicKeyResponse.Merge(m, src)
}
func (m *QueryKyberPublicKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryKyberPublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKyberPublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKyberPublicKeyResponse proto.InternalMessageInfo

func (m *QueryKyberPublicKeyResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type QueryEncryptedMessageRequest struct {
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (m *QueryEncryptedMessageRequest) Reset()         { *m = QueryEncryptedMessageRequest{} }
func (m *QueryEncryptedMessageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEncryptedMessageRequest) ProtoMessage()    {}
func (*QueryEncryptedMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b3d2129c030bc, []int{2}
}
func (m *QueryEncryptedMessageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEncryptedMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEncryptedMessageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEncryptedMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEncryptedMessageRequest.Merge(m, src)
}
func (m *QueryEncryptedMessageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEncryptedMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEncryptedMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEncryptedMessageRequest proto.InternalMessageInfo

func (m *QueryEncryptedMessageRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type QueryEncryptedMessageResponse struct {
	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *QueryEncryptedMessageResponse) Reset()         { *m = QueryEncryptedMessageResponse{} }
func (m *QueryEncryptedMessageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEncryptedMessageResponse) ProtoMessage()    {}
func (*QueryEncryptedMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b3d2129c030bc, []int{3}
}
func (m *QueryEncryptedMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEncryptedMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEncryptedMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEncryptedMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEncryptedMessageResponse.Merge(m, src)
}
func (m *QueryEncryptedMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEncryptedMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEncryptedMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEncryptedMessageResponse proto.InternalMessageInfo

func (m *QueryEncryptedMessageResponse) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryKyberPublicKeyRequest)(nil), "baronchain.pqc.QueryKyberPublicKeyRequest")
	proto.RegisterType((*QueryKyberPublicKeyResponse)(nil), "baronchain.pqc.QueryKyberPublicKeyResponse")
	proto.RegisterType((*QueryEncryptedMessageRequest)(nil), "baronchain.pqc.QueryEncryptedMessageRequest")
	proto.RegisterType((*QueryEncryptedMessageResponse)(nil), "baronchain.pqc.QueryEncryptedMessageResponse")
}

func init() { proto.RegisterFile("baronchain/pqc/query.proto", fileDescriptor_c20b3d2129c030bc) }

var fileDescriptor_c20b3d2129c030bc = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0x0a, 0xdf, 0x27, 0x1d, 0xa4, 0xc8, 0x20, 0x52, 0x62, 0x1b, 0x24, 0xfe, 0x20, 0xb6,
	0x66, 0x44, 0xc1, 0x55, 0x41, 0x10, 0x5c, 0x15, 0x41, 0xbb, 0x74, 0x23, 0x49, 0x7a, 0x49, 0x83,
	0x75, 0x66, 0x32, 0x33, 0x85, 0x86, 0xd2, 0x8d, 0x4f, 0x20, 0xb8, 0x70, 0xe3, 0xc3, 0xb8, 0x74,
	0x59, 0x70, 0xe3, 0x52, 0x5a, 0x1f, 0x44, 0x3a, 0x49, 0xed, 0x0f, 0x2d, 0x74, 0x97, 0xdc, 0x7b,
	0xce, 0x3d, 0xe7, 0x9e, 0x3b, 0xc8, 0xf4, 0x5c, 0xc1, 0xa8, 0xdf, 0x74, 0x43, 0x4a, 0x78, 0xe4,
	0x93, 0xa8, 0x0d, 0x22, 0x76, 0xb8, 0x60, 0x8a, 0xe1, 0xfc, 0xa4, 0xe7, 0xf0, 0xc8, 0x37, 0x37,
	0x03, 0x16, 0x30, 0xdd, 0x22, 0xa3, 0xaf, 0x04, 0x65, 0x16, 0x03, 0xc6, 0x82, 0x16, 0x10, 0x97,
	0x87, 0xc4, 0xa5, 0x94, 0x29, 0x57, 0x85, 0x8c, 0xca, 0xa4, 0x6b, 0x9f, 0x23, 0xf3, 0x76, 0x34,
	0xb2, 0x16, 0x7b, 0x20, 0x6e, 0xda, 0x5e, 0x2b, 0xf4, 0x6b, 0x10, 0xd7, 0x21, 0x6a, 0x83, 0x54,
	0xb8, 0x80, 0xd6, 0xdc, 0x46, 0x43, 0x80, 0x94, 0x05, 0x63, 0xc7, 0x38, 0xcc, 0xd5, 0xc7, 0xbf,
	0x76, 0x15, 0x6d, 0x2f, 0xe4, 0x49, 0xce, 0xa8, 0x04, 0x5c, 0x42, 0x88, 0xeb, 0xe2, 0xfd, 0x03,
	0xc4, 0x9a, 0xbb, 0x5e, 0xcf, 0xf1, 0x31, 0xcc, 0xae, 0xa2, 0xa2, 0x66, 0x5f, 0x51, 0x5f, 0xc4,
	0x5c, 0x41, 0xe3, 0x1a, 0xa4, 0x74, 0x03, 0x18, 0xeb, 0x16, 0x51, 0x4e, 0x80, 0x1f, 0xf2, 0x10,
	0xa8, 0x4a, 0x95, 0x27, 0x05, 0xfb, 0x02, 0x95, 0x96, 0xb0, 0x53, 0x75, 0x0b, 0x21, 0x3f, 0xe4,
	0x4d, 0x10, 0x0a, 0x3a, 0x2a, 0x55, 0x9f, 0xaa, 0x9c, 0xbe, 0x67, 0xd1, 0x3f, 0x3d, 0x01, 0xbf,
	0x1a, 0x28, 0x3f, 0xbb, 0x02, 0x3e, 0x72, 0x66, 0x63, 0x75, 0x96, 0xe7, 0x63, 0x96, 0x57, 0xc2,
	0x26, 0xae, 0xec, 0xca, 0xd3, 0xe7, 0xcf, 0x4b, 0xf6, 0x00, 0xef, 0x91, 0xb9, 0x9b, 0x4e, 0x92,
	0x22, 0xdd, 0x34, 0xdf, 0x1e, 0x7e, 0x33, 0xd0, 0xc6, 0xfc, 0x82, 0xb8, 0xb2, 0x50, 0x6f, 0x49,
	0x8a, 0xe6, 0xf1, 0x8a, 0xe8, 0xd4, 0x5f, 0x59, 0xfb, 0xdb, 0xc7, 0xbb, 0xf3, 0xfe, 0x1e, 0x13,
	0x20, 0xe9, 0xfe, 0x9d, 0xa0, 0x77, 0x79, 0xf2, 0x31, 0xb0, 0x8c, 0xfe, 0xc0, 0x32, 0xbe, 0x07,
	0x96, 0xf1, 0x3c, 0xb4, 0x32, 0xfd, 0xa1, 0x95, 0xf9, 0x1a, 0x5a, 0x99, 0xbb, 0xad, 0x29, 0x76,
	0x47, 0xf3, 0x55, 0xcc, 0x41, 0x7a, 0xff, 0xf5, 0x83, 0x3b, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x00, 0xac, 0x65, 0x49, 0xd2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// KyberPublicKey queries a public key by address
	KyberPublicKey(ctx context.Context, in *QueryKyberPublicKeyRequest, opts ...grpc.CallOption) (*QueryKyberPublicKeyResponse, error)
	// EncryptedMessage queries an encrypted message by recipient
	EncryptedMessage(ctx context.Context, in *QueryEncryptedMessageRequest, opts ...grpc.CallOption) (*QueryEncryptedMessageResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) KyberPublicKey(ctx context.Context, in *QueryKyberPublicKeyRequest, opts ...grpc.CallOption) (*QueryKyberPublicKeyResponse, error) {
	out := new(QueryKyberPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/baronchain.pqc.Query/KyberPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EncryptedMessage(ctx context.Context, in *QueryEncryptedMessageRequest, opts ...grpc.CallOption) (*QueryEncryptedMessageResponse, error) {
	out := new(QueryEncryptedMessageResponse)
	err := c.cc.Invoke(ctx, "/baronchain.pqc.Query/EncryptedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// KyberPublicKey queries a public key by address
	KyberPublicKey(context.Context, *QueryKyberPublicKeyRequest) (*QueryKyberPublicKeyResponse, error)
	// EncryptedMessage queries an encrypted message by recipient
	EncryptedMessage(context.Context, *QueryEncryptedMessageRequest) (*QueryEncryptedMessageResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) KyberPublicKey(ctx context.Context, req *QueryKyberPublicKeyRequest) (*QueryKyberPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KyberPublicKey not implemented")
}
func (*UnimplementedQueryServer) EncryptedMessage(ctx context.Context, req *QueryEncryptedMessageRequest) (*QueryEncryptedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptedMessage not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_KyberPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKyberPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KyberPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baronchain.pqc.Query/KyberPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KyberPublicKey(ctx, req.(*QueryKyberPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EncryptedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEncryptedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EncryptedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baronchain.pqc.Query/EncryptedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EncryptedMessage(ctx, req.(*QueryEncryptedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "baronchain.pqc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KyberPublicKey",
			Handler:    _Query_KyberPublicKey_Handler,
		},
		{
			MethodName: "EncryptedMessage",
			Handler:    _Query_EncryptedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baronchain/pqc/query.proto",
}

func (m *QueryKyberPublicKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKyberPublicKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKyberPublicKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryKyberPublicKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKyberPublicKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKyberPublicKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEncryptedMessageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEncryptedMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEncryptedMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEncryptedMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEncryptedMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEncryptedMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryKyberPublicKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryKyberPublicKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEncryptedMessageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEncryptedMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryKyberPublicKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKyberPublicKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKyberPublicKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryKyberPublicKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKyberPublicKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKyberPublicKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEncryptedMessageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEncryptedMessageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEncryptedMessageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEncryptedMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEncryptedMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEncryptedMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
