// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baronchain/pqc/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgStoreKyberPublicKey struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *MsgStoreKyberPublicKey) Reset()         { *m = MsgStoreKyberPublicKey{} }
func (m *MsgStoreKyberPublicKey) String() string { return proto.CompactTextString(m) }
func (*MsgStoreKyberPublicKey) ProtoMessage()    {}
func (*MsgStoreKyberPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_644bd6ef395efd67, []int{0}
}
func (m *MsgStoreKyberPublicKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStoreKyberPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStoreKyberPublicKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStoreKyberPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStoreKyberPublicKey.Merge(m, src)
}
func (m *MsgStoreKyberPublicKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgStoreKyberPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStoreKyberPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStoreKyberPublicKey proto.InternalMessageInfo

func (m *MsgStoreKyberPublicKey) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStoreKyberPublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type MsgStoreKyberPublicKeyResponse struct {
}

func (m *MsgStoreKyberPublicKeyResponse) Reset()         { *m = MsgStoreKyberPublicKeyResponse{} }
func (m *MsgStoreKyberPublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStoreKyberPublicKeyResponse) ProtoMessage()    {}
func (*MsgStoreKyberPublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644bd6ef395efd67, []int{1}
}
func (m *MsgStoreKyberPublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStoreKyberPublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStoreKyberPublicKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStoreKyberPublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStoreKyberPublicKeyResponse.Merge(m, src)
}
func (m *MsgStoreKyberPublicKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStoreKyberPublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStoreKyberPublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStoreKyberPublicKeyResponse proto.InternalMessageInfo

type MsgSendEncryptedMessage struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Recipient  string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Ciphertext []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *MsgSendEncryptedMessage) Reset()         { *m = MsgSendEncryptedMessage{} }
func (m *MsgSendEncryptedMessage) String() string { return proto.CompactTextString(m) }
func (*MsgSendEncryptedMessage) ProtoMessage()    {}
func (*MsgSendEncryptedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_644bd6ef395efd67, []int{2}
}
func (m *MsgSendEncryptedMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendEncryptedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendEncryptedMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendEncryptedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendEncryptedMessage.Merge(m, src)
}
func (m *MsgSendEncryptedMessage) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendEncryptedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendEncryptedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendEncryptedMessage proto.InternalMessageInfo

func (m *MsgSendEncryptedMessage) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendEncryptedMessage) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgSendEncryptedMessage) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type MsgSendEncryptedMessageResponse struct {
}

func (m *MsgSendEncryptedMessageResponse) Reset()         { *m = MsgSendEncryptedMessageResponse{} }
func (m *MsgSendEncryptedMessageResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendEncryptedMessageResponse) ProtoMessage()    {}
func (*MsgSendEncryptedMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644bd6ef395efd67, []int{3}
}
func (m *MsgSendEncryptedMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendEncryptedMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendEncryptedMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendEncryptedMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendEncryptedMessageResponse.Merge(m, src)
}
func (m *MsgSendEncryptedMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendEncryptedMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendEncryptedMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendEncryptedMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgStoreKyberPublicKey)(nil), "baronchain.pqc.MsgStoreKyberPublicKey")
	proto.RegisterType((*MsgStoreKyberPublicKeyResponse)(nil), "baronchain.pqc.MsgStoreKyberPublicKeyResponse")
	proto.RegisterType((*MsgSendEncryptedMessage)(nil), "baronchain.pqc.MsgSendEncryptedMessage")
	proto.RegisterType((*MsgSendEncryptedMessageResponse)(nil), "baronchain.pqc.MsgSendEncryptedMessageResponse")
}

func init() { proto.RegisterFile("baronchain/pqc/tx.proto", fileDescriptor_644bd6ef395efd67) }

var fileDescriptor_644bd6ef395efd67 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x17, 0x07, 0x4a, 0x1f, 0xe2, 0x21, 0xca, 0x56, 0x86, 0xc6, 0xd9, 0x83, 0xee, 0xd4,
	0x89, 0x7e, 0x03, 0xc1, 0xd3, 0x28, 0x68, 0xbd, 0x79, 0x91, 0x36, 0x7b, 0x74, 0x45, 0x4d, 0xd2,
	0x24, 0x42, 0xfb, 0x2d, 0xfc, 0x58, 0x1e, 0x77, 0xf4, 0x28, 0x2d, 0xf8, 0x39, 0xc4, 0x4a, 0xd9,
	0x84, 0x28, 0x3b, 0xe6, 0xe5, 0x97, 0xf7, 0x7b, 0x79, 0xfc, 0x61, 0x98, 0x26, 0x5a, 0x0a, 0xbe,
	0x48, 0x72, 0x31, 0x55, 0x05, 0x9f, 0xda, 0x32, 0x54, 0x5a, 0x5a, 0x49, 0xf7, 0x56, 0x17, 0xa1,
	0x2a, 0x78, 0x70, 0x0b, 0x83, 0xc8, 0x64, 0x77, 0x56, 0x6a, 0x9c, 0x55, 0x29, 0xea, 0x9b, 0x97,
	0xf4, 0x29, 0xe7, 0x33, 0xac, 0xa8, 0x0f, 0x3b, 0x5c, 0x63, 0x62, 0xa5, 0xf6, 0xc9, 0x98, 0x4c,
	0xbc, 0xb8, 0x3b, 0xd2, 0x23, 0x00, 0xd5, 0x62, 0x0f, 0x8f, 0x58, 0xf9, 0x5b, 0x63, 0x32, 0xd9,
	0x8d, 0x3d, 0xd5, 0x3d, 0x0c, 0xc6, 0xc0, 0xdc, 0x2d, 0x63, 0x34, 0x4a, 0x0a, 0x83, 0x41, 0x01,
	0xc3, 0x6f, 0x02, 0xc5, 0xfc, 0x5a, 0x70, 0x5d, 0x29, 0x8b, 0xf3, 0x08, 0x8d, 0x49, 0x32, 0xfc,
	0xc7, 0x7a, 0x08, 0x9e, 0x46, 0x9e, 0xab, 0x1c, 0x85, 0x6d, 0xa5, 0x5e, 0xbc, 0x2a, 0x50, 0x06,
	0xc0, 0x73, 0xb5, 0x40, 0x6d, 0xb1, 0xb4, 0x7e, 0xbf, 0x9d, 0x69, 0xad, 0x12, 0x9c, 0xc0, 0xf1,
	0x1f, 0xca, 0x6e, 0xaa, 0x8b, 0x4f, 0x02, 0xfd, 0xc8, 0x64, 0xf4, 0x19, 0xf6, 0x5d, 0xfb, 0x38,
	0x0d, 0x7f, 0xaf, 0x2e, 0x74, 0x7f, 0x72, 0x14, 0x6e, 0xc6, 0x75, 0x5a, 0xaa, 0xe0, 0xc0, 0xb9,
	0x89, 0x33, 0x57, 0x1f, 0x07, 0x38, 0x9a, 0x6e, 0x08, 0x76, 0xc6, 0xab, 0xf3, 0xb7, 0x9a, 0x91,
	0x65, 0xcd, 0xc8, 0x47, 0xcd, 0xc8, 0x6b, 0xc3, 0x7a, 0xcb, 0x86, 0xf5, 0xde, 0x1b, 0xd6, 0xbb,
	0x1f, 0xac, 0xc5, 0xa6, 0xfc, 0x09, 0x4e, 0xa5, 0xd0, 0xa4, 0xdb, 0x6d, 0x78, 0x2e, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x0b, 0xed, 0xa3, 0x57, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StoreKyberPublicKey(ctx context.Context, in *MsgStoreKyberPublicKey, opts ...grpc.CallOption) (*MsgStoreKyberPublicKeyResponse, error)
	SendEncryptedMessage(ctx context.Context, in *MsgSendEncryptedMessage, opts ...grpc.CallOption) (*MsgSendEncryptedMessageResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StoreKyberPublicKey(ctx context.Context, in *MsgStoreKyberPublicKey, opts ...grpc.CallOption) (*MsgStoreKyberPublicKeyResponse, error) {
	out := new(MsgStoreKyberPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/baronchain.pqc.Msg/StoreKyberPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendEncryptedMessage(ctx context.Context, in *MsgSendEncryptedMessage, opts ...grpc.CallOption) (*MsgSendEncryptedMessageResponse, error) {
	out := new(MsgSendEncryptedMessageResponse)
	err := c.cc.Invoke(ctx, "/baronchain.pqc.Msg/SendEncryptedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StoreKyberPublicKey(context.Context, *MsgStoreKyberPublicKey) (*MsgStoreKyberPublicKeyResponse, error)
	SendEncryptedMessage(context.Context, *MsgSendEncryptedMessage) (*MsgSendEncryptedMessageResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StoreKyberPublicKey(ctx context.Context, req *MsgStoreKyberPublicKey) (*MsgStoreKyberPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreKyberPublicKey not implemented")
}
func (*UnimplementedMsgServer) SendEncryptedMessage(ctx context.Context, req *MsgSendEncryptedMessage) (*MsgSendEncryptedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEncryptedMessage not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StoreKyberPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStoreKyberPublicKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StoreKyberPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baronchain.pqc.Msg/StoreKyberPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StoreKyberPublicKey(ctx, req.(*MsgStoreKyberPublicKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendEncryptedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendEncryptedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendEncryptedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baronchain.pqc.Msg/SendEncryptedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendEncryptedMessage(ctx, req.(*MsgSendEncryptedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "baronchain.pqc.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreKyberPublicKey",
			Handler:    _Msg_StoreKyberPublicKey_Handler,
		},
		{
			MethodName: "SendEncryptedMessage",
			Handler:    _Msg_SendEncryptedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baronchain/pqc/tx.proto",
}

func (m *MsgStoreKyberPublicKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStoreKyberPublicKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStoreKyberPublicKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStoreKyberPublicKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStoreKyberPublicKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStoreKyberPublicKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendEncryptedMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendEncryptedMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendEncryptedMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendEncryptedMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendEncryptedMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendEncryptedMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgStoreKyberPublicKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStoreKyberPublicKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendEncryptedMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendEncryptedMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgStoreKyberPublicKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStoreKyberPublicKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStoreKyberPublicKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStoreKyberPublicKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStoreKyberPublicKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStoreKyberPublicKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendEncryptedMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendEncryptedMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendEncryptedMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendEncryptedMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendEncryptedMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendEncryptedMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
