// proto/baronchain/pqc/query.proto
syntax = "proto3";
package baronchain.pqc;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "baronchain/pqc/params.proto";

option go_package = "baronchain/x/pqc/types";

// Query defines the gRPC querier service.
service Query {
  // KyberPublicKey queries a public key by address
  rpc KyberPublicKey(QueryKyberPublicKeyRequest) returns (QueryKyberPublicKeyResponse) {
    option (google.api.http).get = "/baronchain/pqc/public_key/{address}";
  }
  
  // EncryptedMessage queries an encrypted message by recipient
  rpc EncryptedMessage(QueryEncryptedMessageRequest) returns (QueryEncryptedMessageResponse) {
    option (google.api.http).get = "/baronchain/pqc/message/{recipient}";
  }

  // Params queries all parameters of the PQC module
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/baronchain/pqc/params";
  }
}

message QueryKyberPublicKeyRequest {
  string address = 1;
}

message QueryKyberPublicKeyResponse {
  bytes public_key = 1;
}

message QueryEncryptedMessageRequest {
  string recipient = 1;
}

message QueryEncryptedMessageResponse {
  bytes ciphertext = 1;
}

// QueryParamsRequest is the request type for the Query/Params RPC method
message QueryParamsRequest {}

// QueryParamsResponse is the response type for the Query/Params RPC method
message QueryParamsResponse {
  Params params = 1 [(gogoproto.nullable) = false];
}